version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: Youtube.Api_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  youtube.api:
    image: ${DOCKER_REGISTRY-}youtubeapi
    build:
      context: .
      dockerfile: Youtube.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Host=postgres;Port=5432;Database=Youtube.Api_DB;Username=postgres;Password=postgres
    depends_on:
      - postgres
    ports:
      - "8080:80"
      - "8081:443"
